package sc.fiji.oc3dplus.equivalence;

import org.junit.Assume;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.fail;

/**
 * <b>The ship gate.</b> Runs the corpus against the current build and applies the
 * tier contract to every golden.
 *
 * <p>Tier 1 differences fail. Tier 2 differences fail only outside their declared
 * bound. Tier 3 differences are printed for sign-off and do not fail, because they
 * are known algorithmic changes - but they are never silent.
 *
 * <p>The Tier 2 delta table is printed on every run, pass or fail, because it is a
 * required deliverable of each migration stage and not merely diagnostic output.
 */
public class EquivalenceHarnessTest {

    @Rule
    public TemporaryFolder temporary = new TemporaryFolder();

    @Test
    public void currentBuildMatchesGoldens() throws Exception {
        Assume.assumeFalse("no golden set at " + GoldenStore.directory().getAbsolutePath()
                        + "; run CaptureGoldensTest against the pre-migration build first",
                GoldenStore.isEmpty());

        final Differ.Report report = new Differ.Report();
        final List<String> missing = new ArrayList<String>();
        // Streamed one golden at a time: the corpus does not fit in memory twice.
        HarnessRun.forEachGolden(temporary.newFolder("batch"), new HarnessRun.Visitor() {
            @Override public void visit(String goldenName, List<CaptureRecord> records)
                    throws IOException {
                List<CaptureRecord> goldens = GoldenStore.read(goldenName);
                if (goldens == null) {
                    missing.add(goldenName);
                    return;
                }
                Differ.Report perFixture = Differ.diff(goldens, records);
                report.findings.addAll(perFixture.findings);
                for (Differ.Delta delta : perFixture.deltaTable()) {
                    Differ.Delta target = report.delta(delta.harnessCase, delta.column);
                    target.compared += delta.compared;
                    target.nonZero += delta.nonZero;
                    target.outsideBound += delta.outsideBound;
                    target.relative.addAll(delta.relative);
                }
            }
        });

        System.out.println("=== Tier 2 delta table (relative differences) ===");
        List<Differ.Delta> deltas = report.deltaTable();
        for (int i = 0; i < deltas.size(); i++) {
            System.out.println("  " + deltas.get(i).describe());
        }
        saveDeltaTable(deltas, report);

        List<Differ.Finding> tier3 = report.tier(3);
        if (!tier3.isEmpty()) {
            System.out.println("=== Tier 3, requires written sign-off (" + tier3.size() + ") ===");
            for (int i = 0; i < Math.min(tier3.size(), 50); i++) {
                System.out.println("  " + tier3.get(i));
            }
            if (tier3.size() > 50) {
                System.out.println("  ... " + (tier3.size() - 50) + " more not printed");
            }
        }

        StringBuilder failure = new StringBuilder();
        if (!missing.isEmpty()) {
            failure.append("no golden file for: ")
                    .append(ColumnContract.join(missing, ", ")).append('\n');
        }
        appendFindings(failure, "TIER 1", report.tier(1));
        appendFindings(failure, "TIER 2 outside declared bound (or a Tier 2 mismatch with no bound, "
                + "such as a column reorder)", report.tier(2));
        if (failure.length() > 0) {
            fail("Equivalence harness failed (" + report.summarise() + "):\n" + failure);
        }
    }

    /**
     * Writes the delta table to {@code target/equivalence/tier2-delta-table.md}.
     *
     * <p>The table is a required deliverable of every migration stage, and a
     * deliverable that exists only as console output of a run nobody kept is not
     * one. Writing it under {@code target/} keeps it regenerated by the same
     * command that produces it, rather than transcribed by hand into a document
     * that then drifts.
     *
     * <p>Each row carries the declared tier and rule alongside the measured
     * spread, because a large relative difference in a Tier 3 column and the same
     * number in a Tier 2 column mean opposite things.
     */
    private static void saveDeltaTable(List<Differ.Delta> deltas, Differ.Report report)
            throws IOException {
        StringBuilder out = new StringBuilder();
        out.append("# Tier 2 delta table\n\n");
        out.append("Written by `EquivalenceHarnessTest` on every run. Harness summary: ")
                .append(report.summarise()).append(".\n\n");
        out.append("`outsideBound` counts cells that broke their declared bound. It must be ")
                .append("zero on every row; a non-zero entry is a stage-blocking failure and ")
                .append("the run above will have failed with it.\n\n");
        out.append("Relative difference is `|candidate - golden| / max(|golden|, |candidate|)`, ")
                .append("accumulated per (case, column) across the whole corpus and ")
                .append("configuration sweep.\n\n");
        out.append("| Case | Column | Tier | Rule | Bound | Compared | Non-zero | Outside bound "
                + "| Median | p95 | Max |\n");
        out.append("|---|---|---|---|---|---|---|---|---|---|---|\n");
        for (int i = 0; i < deltas.size(); i++) {
            Differ.Delta delta = deltas.get(i);
            ColumnContract.Entry entry = ColumnContract.lookup(delta.column, delta.harnessCase);
            out.append("| ").append(delta.harnessCase)
                    .append(" | `").append(delta.column).append('`')
                    .append(" | ").append(entry == null ? "?" : Integer.toString(entry.tier))
                    .append(" | ").append(entry == null ? "?" : entry.rule.token())
                    .append(" | ").append(entry == null || Double.isNaN(entry.bound)
                            ? "-" : Double.toString(entry.bound))
                    .append(" | ").append(delta.compared)
                    .append(" | ").append(delta.nonZero)
                    .append(" | ").append(delta.outsideBound)
                    .append(" | ").append(CaptureRecord.number(delta.median()))
                    .append(" | ").append(CaptureRecord.number(delta.p95()))
                    .append(" | ").append(CaptureRecord.number(delta.max()))
                    .append(" |\n");
        }
        File directory = new File("target", "equivalence");
        if (!directory.isDirectory() && !directory.mkdirs()) {
            throw new IOException("Could not create " + directory);
        }
        File file = new File(directory, "tier2-delta-table.md");
        Files.write(file.toPath(), out.toString().getBytes(StandardCharsets.UTF_8));
        System.out.println("wrote " + file.getAbsolutePath());
    }

    private static void appendFindings(StringBuilder out, String label, List<Differ.Finding> findings) {
        if (findings.isEmpty()) return;
        out.append(label).append(" (").append(findings.size()).append("):\n");
        for (int i = 0; i < Math.min(findings.size(), 60); i++) {
            out.append("  ").append(findings.get(i)).append('\n');
        }
        if (findings.size() > 60) {
            out.append("  ... ").append(findings.size() - 60).append(" more\n");
        }
    }
}
