package sc.fiji.oc3dplus.equivalence;

import ij.ImagePlus;
import ij.io.FileInfo;
import ij.io.TiffDecoder;
import ij.plugin.FileInfoVirtualStack;
import org.junit.Assume;
import org.junit.Test;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;

/**
 * Reports the dimensions of nominated real stacks without opening them, so the
 * real-data corpus can be assembled from facts rather than from file sizes.
 *
 * <pre>
 * mvn -o -B test -Dtest=RealCorpusProbeTest -Doc3dplus.realCorpus=docs/migration/real-corpus.txt
 * </pre>
 *
 * <p>The list is one path per line; blank lines and {@code #} comments are ignored.
 * Only headers are read, so a 17 GB stack costs milliseconds.
 *
 * <p>Two of the release-note claims depend on what this finds:
 *
 * <ul>
 *   <li>The 2<sup>31</sup>-voxel ceiling was removed <b>by inspection only</b> - no
 *       flat {@code int length = w*h*d} exists - and has never been tested. It can
 *       only be claimed if a stack above 2,147,483,647 voxels exists to run.</li>
 *   <li>A stack that fails today with {@code NegativeArraySizeException} is the
 *       most persuasive before/after in the release notes, and needs identifying
 *       rather than assuming.</li>
 * </ul>
 *
 * <p>If no such stack is in the corpus, the corresponding claim gets dropped. The
 * probe exists so that decision is made on evidence.
 *
 * <p>Reads TIFF headers only. Bio-Formats formats such as {@code .lif} need the
 * Bio-Formats reader, which is not on this test classpath; those are reported as
 * unreadable here rather than silently skipped.
 */
public class RealCorpusProbeTest {

    private static final String LIST_PROPERTY = "oc3dplus.realCorpus";
    private static final long INT_VOXEL_CEILING = 2147483647L;

    @Test
    public void probeNominatedStacks() throws Exception {
        String configured = System.getProperty(LIST_PROPERTY);
        Assume.assumeTrue("set -D" + LIST_PROPERTY + "=<file or semicolon-separated paths> "
                        + "to probe the real corpus",
                configured != null && !configured.trim().isEmpty());

        List<String> paths = resolve(configured.trim());
        System.out.println("=== real corpus probe: " + paths.size() + " path(s) ===");
        int aboveCeiling = 0;
        for (int i = 0; i < paths.size(); i++) {
            String line = describe(paths.get(i));
            System.out.println(line);
            if (line.contains("ABOVE-2^31")) aboveCeiling++;
        }
        System.out.println("stacks above the 2^31-voxel ceiling: " + aboveCeiling
                + (aboveCeiling == 0
                        ? " - the ceiling-removal claim cannot be tested from this list"
                        : " - the ceiling-removal claim is testable"));
    }

    /**
     * Writes {@code docs/migration/REAL_CORPUS_MANIFEST.md}: path, size, dimensions
     * and SHA-256 for every nominated stack.
     *
     * <pre>
     * mvn -o -B test -Dtest=RealCorpusProbeTest -Doc3dplus.realCorpus=docs/migration/real-corpus.txt \
     *     -Doc3dplus.realCorpusManifest=true
     * </pre>
     *
     * <p>Harness §6 keeps real goldens outside the repository and commits a manifest
     * of paths and checksums instead - the images are far too large to version, and
     * {@code .tif} is gitignored here for that reason. The checksum is what makes a
     * real golden meaningful later: it pins which bytes produced it, so a re-run
     * that silently picked up a re-exported file is detectable rather than
     * mysterious.
     */
    @Test
    public void writeManifest() throws Exception {
        String configured = System.getProperty(LIST_PROPERTY);
        Assume.assumeTrue("set -D" + LIST_PROPERTY + " and -Doc3dplus.realCorpusManifest=true",
                configured != null && !configured.trim().isEmpty()
                        && Boolean.getBoolean("oc3dplus.realCorpusManifest"));

        List<String> paths = resolve(configured.trim());
        StringBuilder out = new StringBuilder();
        out.append("# Real-data corpus manifest\n\n");
        out.append("Generated by `RealCorpusProbeTest#writeManifest` from ")
                .append("`docs/migration/real-corpus.txt`.\n\n");
        out.append("The images live outside the repository and are not versioned: `*.tif` is ")
                .append("gitignored, and the corpus is ~11 GB. This manifest is the committed ")
                .append("record of exactly which bytes any real golden was captured from.\n\n");
        out.append("Every listed file was already hydrated when the manifest was written; ")
                .append("nothing was downloaded to produce it.\n\n");
        out.append("| # | Size | Dimensions | Voxels | B/px | Ch | Fr | Case | SHA-256 (first 16) | File |\n");
        out.append("|---|---|---|---|---|---|---|---|---|---|\n");

        long totalBytes = 0;
        long aboveCeiling = 0;
        int caseA = 0;
        int caseB = 0;
        for (int i = 0; i < paths.size(); i++) {
            File file = new File(paths.get(i));
            if (!file.isFile()) {
                out.append("| ").append(i + 1).append(" | MISSING | | | | | | | | `")
                        .append(paths.get(i)).append("` |\n");
                continue;
            }
            totalBytes += file.length();
            Dimensions dimensions = dimensionsOf(file);
            if (dimensions.voxels > INT_VOXEL_CEILING) aboveCeiling++;
            // canUseClassicCounter (OC3DPlusRunner:434): 8- or 16-bit, one
            // channel, one frame. Everything else falls to mcib3d.
            boolean classic = (dimensions.bytesPerPixel == 1 || dimensions.bytesPerPixel == 2)
                    && dimensions.channels == 1 && dimensions.frames == 1;
            if (dimensions.width == 0) {
                classic = false;
            } else if (classic) {
                caseA++;
            } else {
                caseB++;
            }
            out.append("| ").append(i + 1)
                    .append(" | ").append(file.length() / (1024 * 1024)).append(" MB")
                    .append(" | ").append(dimensions.describe())
                    .append(" | ").append(dimensions.voxels > 0 ? Long.toString(dimensions.voxels) : "?")
                    .append(dimensions.voxels > INT_VOXEL_CEILING ? " **>2^31**" : "")
                    .append(" | ").append(dimensions.bytesPerPixel)
                    .append(" | ").append(dimensions.channels)
                    .append(" | ").append(dimensions.frames)
                    .append(" | ").append(dimensions.width == 0 ? "?" : (classic ? "**A**" : "B"))
                    .append(" | `").append(sha256(file).substring(0, 16)).append("`")
                    .append(" | `").append(file.getName()).append("` |\n");
            System.out.println("  manifest " + (i + 1) + "/" + paths.size() + "  " + file.getName());
        }
        out.append("\n**").append(paths.size()).append(" stacks, ")
                .append(String.format(java.util.Locale.ROOT, "%.2f", totalBytes / (1024.0 * 1024 * 1024)))
                .append(" GB, ").append(aboveCeiling)
                .append(" above the 2^31-voxel ceiling.**\n\n");
        out.append("**Case coverage: ").append(caseA).append(" Case A, ")
                .append(caseB).append(" Case B.**\n\n");
        if (caseA < caseB) {
            out.append("Case A is under-represented, and Case A is the one that must not move - ")
                    .append("it is what the overwhelming majority of users see. The cause is that ")
                    .append("this lab's data is predominantly multi-channel or timelapse, and ")
                    .append("`canUseClassicCounter` (`OC3DPlusRunner:434`) accepts only 8- or ")
                    .append("16-bit, one channel, one frame.\n\n");
            out.append("The Amyloid Project is where the Case A coverage would come from: its ")
                    .append("stacks are single-channel per-marker exports (`DAPI_SCN.tif`, ")
                    .append("`CK1_SCN.tif`, `MOAB-2_SCN.tif`, `mCherry_SCN.tif`), which is exactly ")
                    .append("the Case A shape. All 625 of them fail to open on this machine ")
                    .append("despite carrying no `Offline` attribute, so hydrating that project is ")
                    .append("worth more to this migration than its file count suggests.\n\n");
        }
        out.append("Full checksums are truncated to 16 hex characters in this table for ")
                .append("readability; regenerate the manifest to verify a file in full.\n");

        File manifest = new File("docs" + File.separator + "migration", "REAL_CORPUS_MANIFEST.md");
        Files.write(manifest.toPath(), out.toString().getBytes(StandardCharsets.UTF_8));
        System.out.println("wrote " + manifest.getAbsolutePath());
    }

    private static final class Dimensions {
        int width;
        int height;
        int slices;
        int bytesPerPixel;
        int channels = 1;
        int frames = 1;
        long voxels;
        String note = "";

        String describe() {
            if (width == 0) return "unreadable" + note;
            return width + "x" + height + "x" + slices + note;
        }
    }

    private static Dimensions dimensionsOf(File file) {
        Dimensions out = new Dimensions();
        String lower = file.getName().toLowerCase(java.util.Locale.ROOT);
        if (!lower.endsWith(".tif") && !lower.endsWith(".tiff")) {
            out.note = " (needs Bio-Formats)";
            return out;
        }
        try {
            FileInfo[] info = new TiffDecoder(file.getParent(), file.getName()).getTiffInfo();
            if (info == null || info.length == 0) return out;
            out.width = info[0].width;
            out.height = info[0].height;
            out.bytesPerPixel = info[0].getBytesPerPixel();
            int ifds = info.length;
            out.slices = ifds == 1 && info[0].nImages > 1 ? info[0].nImages : ifds;
            out.voxels = (long) out.width * out.height * out.slices;
            long impliedSlices = out.bytesPerPixel > 0 && out.width > 0
                    ? file.length() / out.bytesPerPixel / ((long) out.width * out.height) : 0;
            if (impliedSlices > out.slices * 2L) {
                out.note = " (size implies ~" + impliedSlices + ")";
                out.voxels = (long) out.width * out.height * impliedSlices;
            }
            // Channel and frame counts come from the TIFF's own ImageDescription,
            // never by opening the image. Opening is not safe here: a compressed
            // TIFF cannot back a virtual stack, so ImageJ silently falls back to a
            // full load, and a 3 GB file then exhausts the heap. Reading metadata
            // has no such cliff.
            out.channels = Math.max(1, fromDescription(info[0].description, "channels"));
            out.frames = Math.max(1, fromDescription(info[0].description, "frames"));
            return out;
        } catch (Exception unreadable) {
            return out;
        }
    }

    /** Reads {@code key=<int>} out of an ImageJ TIFF ImageDescription, or 0. */
    private static int fromDescription(String description, String key) {
        if (description == null) return 0;
        String[] lines = description.split("\\R");
        for (int i = 0; i < lines.length; i++) {
            String line = lines[i].trim();
            if (!line.startsWith(key + "=")) continue;
            try {
                return Integer.parseInt(line.substring(key.length() + 1).trim());
            } catch (NumberFormatException malformed) {
                return 0;
            }
        }
        return 0;
    }

    /**
     * SHA-256, or a recorded reason. A file can carry no {@code Offline} attribute
     * and still fail to open - observed on this machine, where the attribute is not
     * a reliable hydration indicator - so the manifest reports that rather than
     * aborting and losing the rows already computed.
     */
    private static String sha256(File file) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        InputStream stream;
        try {
            stream = new BufferedInputStream(new FileInputStream(file), 1 << 20);
        } catch (java.io.IOException unopenable) {
            return "UNREADABLE------";
        }
        try {
            byte[] buffer = new byte[1 << 20];
            int read;
            while ((read = stream.read(buffer)) > 0) {
                digest.update(buffer, 0, read);
            }
        } finally {
            stream.close();
        }
        byte[] bytes = digest.digest();
        StringBuilder hex = new StringBuilder(bytes.length * 2);
        for (int i = 0; i < bytes.length; i++) {
            int value = bytes[i] & 0xFF;
            if (value < 16) hex.append('0');
            hex.append(Integer.toHexString(value));
        }
        return hex.toString();
    }

    private static List<String> resolve(String configured) throws Exception {
        File asFile = new File(configured);
        List<String> out = new ArrayList<String>();
        if (asFile.isFile()) {
            List<String> lines = Files.readAllLines(asFile.toPath(), StandardCharsets.UTF_8);
            for (int i = 0; i < lines.size(); i++) {
                String line = lines.get(i).trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                out.add(line);
            }
            return out;
        }
        String[] parts = configured.split(";");
        for (int i = 0; i < parts.length; i++) {
            String path = parts[i].trim();
            if (!path.isEmpty()) out.add(path);
        }
        return out;
    }

    private static String describe(String path) {
        File file = new File(path);
        if (!file.isFile()) return "  MISSING  " + path;
        String name = file.getName();
        long megabytes = file.length() / (1024 * 1024);
        String lower = name.toLowerCase(java.util.Locale.ROOT);
        if (!lower.endsWith(".tif") && !lower.endsWith(".tiff")) {
            return "  NEEDS-BIO-FORMATS  " + megabytes + " MB  " + name
                    + "  (header not readable by ij.io.TiffDecoder)";
        }
        try {
            TiffDecoder decoder = new TiffDecoder(file.getParent(), name);
            FileInfo[] info = decoder.getTiffInfo();
            if (info == null || info.length == 0) {
                return "  UNREADABLE  " + megabytes + " MB  " + name;
            }
            int width = info[0].width;
            int height = info[0].height;
            int bytesPerPixel = info[0].getBytesPerPixel();
            int ifds = info.length;
            int declaredImages = info[0].nImages;
            int slices = ifds == 1 && declaredImages > 1 ? declaredImages : ifds;
            long voxels = (long) width * height * slices;

            // Cross-check against the file size. An OME-TIFF can describe its plane
            // count in OME-XML rather than in one IFD per plane, so the IFD count
            // can badly under-report the stack. Reporting a confidently wrong depth
            // would be worse than reporting the disagreement.
            long voxelsFromSize = bytesPerPixel > 0
                    ? file.length() / bytesPerPixel : 0;
            long impliedSlices = (long) width * height > 0
                    ? voxelsFromSize / ((long) width * height) : 0;
            boolean disagrees = impliedSlices > slices * 2L;

            long reportedVoxels = disagrees ? voxelsFromSize : voxels;
            String flag = reportedVoxels > INT_VOXEL_CEILING ? "  ABOVE-2^31" : "";
            return (disagrees ? "  CHECK" : "  OK") + "  " + megabytes + " MB  "
                    + width + "x" + height + "x" + slices
                    + "  voxels=" + voxels
                    + "  type=" + bytesPerPixel + "B/px"
                    + (disagrees
                            ? "  size implies ~" + impliedSlices + " planes (~" + voxelsFromSize
                              + " voxels): IFD count under-reports, open it to confirm"
                            : "")
                    + flag + "  " + name;
        } catch (Exception unreadable) {
            return "  UNREADABLE  " + megabytes + " MB  " + name
                    + "  (" + unreadable.getClass().getSimpleName() + ": "
                    + unreadable.getMessage() + ")";
        }
    }
}
